name: 'Streak Keeper (Never lose your streak.)'
run-name: 'working'

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch
        

      - run: node xp.js
        env:
          lessonsToComplete: 1 
          token: ${{ secrets.TOKEN }}
          userId: ${{ secrets.USER_ID }}
