name: 'Run lessons'
run-name: working.

on:
  workflow_dispatch:
    inputs:
      lessonsToComplete:
        description: 'just like that'
        required: true
        default: 3

  schedule:
    - cron: '34,53 12,17 1 * *'
    - cron: '23 7,11,17 2 * *'
    - cron: '42 6,15,12 3 * *'
    - cron: '12 7,12,18 4 * *'
    - cron: '54,8 15 5 * *'
    - cron: '16,48 7,12 6 * *'
    - cron: '6,26 11,19 7 * *'
    - cron: '36,48 7,13 8 * *'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch

      - run: npm run xp
        env:
          lessonsToComplete: ${{ github.event.inputs.lessonsToComplete }}
          token: ${{ secrets.TOKEN }}
          userId: ${{ secrets.USER_ID }}
