name: 'Get Unlimited Hearts (Permanent)'
run-name: working.

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch

      - run: npm run unlimitedhearts
        env:
          token: ${{ secrets.TOKEN }}
          userId: ${{ secrets.USER_ID }}
